name: Create Release from Changelog

on:
  push:
    tags:
      - 'v*' 

jobs:
  build_release:
    name: Build Release
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ github.ref_name }} 
          path: ./CHANGELOG.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2 
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc') }}